  document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.mobileTab)));document.querySelectorAll('.modal-mask').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));
  document.querySelectorAll('.seg-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.seg-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');serviceType=b.dataset.serviceType;if(serviceType==='solicitacoes'){$('serviceBrowseArea').style.display='none';$('serviceRequestsArea').style.display='block';renderSolicitacoes()}else{$('serviceBrowseArea').style.display='block';$('serviceRequestsArea').style.display='none';serviceCategory='Todos';renderServiceChips();renderServices()}}));
  $('serviceSearch').addEventListener('input',renderServices);$('nearbyOnlyBtn').addEventListener('click',()=>{nearbyOnly=!nearbyOnly;$('nearbyOnlyBtn').textContent=nearbyOnly?'✅ Até 50 km':'📍 Até 50 km';renderServices()});$('productSearch').addEventListener('input',renderProducts);$('sortProducts').addEventListener('change',renderProducts);
  $('fabLancarBtn').addEventListener('click',()=>{$('lancAnimalSelect').innerHTML=animais.map(a=>`<option value="${a.id}">#${a.id} ${a.nome} (atual ${a.prod} L)</option>`).join('');$('lancData').value=today();openModal('modalLancamento')});
  $('confirmarLancamento').addEventListener('click',()=>{const a=animais.find(x=>x.id===$('lancAnimalSelect').value),v=parseFloat($('lancLitros').value);if(!a||isNaN(v)||v<=0)return toast('Informe uma produção válida');const diferenca=v-a.prod;a.prod=v;metricasGerais.producaoTotalDia=Math.max(0,Number(metricasGerais.producaoTotalDia)+diferenca);metricasGerais.mediaVaca=Number((metricasGerais.producaoTotalDia/metricasGerais.vacasLactacao).toFixed(1));const idx=rankingFazendas.findIndex(f=>f.nome.includes('São Pedro'));if(idx>=0)rankingFazendas[idx].producao=metricasGerais.mediaVaca;rankingFazendas.sort((a,b)=>b.producao-a.producao);salvarTudo();renderizarTudo();closeModal('modalLancamento');$('lancLitros').value='';toast('Produção atualizada')});
  $('btnAddTransacao').addEventListener('click',()=>{$('transacaoData').value=today();openModal('modalTransacao')});$('confirmarTransacao').addEventListener('click',()=>{const data=$('transacaoData').value,desc=$('transacaoDesc').value.trim(),valor=parseFloat($('transacaoValor').value);if(!data||!desc||isNaN(valor))return toast('Preencha data, descrição e valor');adicionarTransacao($('tipoTransacao').value,data,desc,$('transacaoCategoria').value,valor);closeModal('modalTransacao');$('transacaoDesc').value='';$('transacaoValor').value='';toast('Movimentação registrada')});
  $('verTodasTransacoes').addEventListener('click',()=>toast('No produto final, aqui abre o extrato completo com filtros e exportação.'));
  $('solicitarServicoBtn').addEventListener('click',()=>{$('selectedServiceSummary').style.display='none';$('modalSolicitar').dataset.provider='Prestadores próximos';$('modalSolicitar').dataset.price='0';$('servicoData').value=today();$('servicoNome').value='';openModal('modalSolicitar')});$('anunciarServicoBtn').addEventListener('click',()=>openModal('modalProvider'));
  $('confirmarSolicitacao').addEventListener('click',()=>{const nome=$('servicoNome').value.trim(),data=$('servicoData').value;if(!nome||!data)return toast('Informe o serviço e a data desejada');const provider=$('modalSolicitar').dataset.provider||'Prestadores próximos';solicitacoes.push({id:Date.now(),data,servico:nome,prestador:provider,valor:0,status:'Orçamento solicitado',financeiro:false});salvarTudo();renderSolicitacoes();closeModal('modalSolicitar');toast('Solicitação enviada aos prestadores')});
  $('headerCartBtn').addEventListener('click',openCart);$('openCartHero').addEventListener('click',openCart);$('checkoutBtn').addEventListener('click',()=>{const total=cartTotal();if(!total)return;const integrar=$('addOrderFinance').checked;if(integrar)adicionarTransacao('despesa',today(),'Pedido Loja LeiteBov','Compras / Insumos',total);cart=[];salvarTudo();renderCart();renderCartCounts();closeModal('modalCart');toast(integrar?'Pedido concluído e lançado no Financeiro':'Pedido de demonstração concluído')});

  carregarDados();$('lancData').value=today();$('servicoData').value=today();renderizarTudo();

  const aiLoader=document.createElement('script');
  aiLoader.src='assistant.js?v=20260911-1310';
  aiLoader.defer=true;
  document.body.appendChild(aiLoader);
