  function renderizarAnimais(){
    $('animalList').innerHTML=animais.map(a=>`<div class="animal-row" onclick="abrirAnimal('${a.id}')"><div class="animal-avatar">🐄</div><div class="animal-info"><div class="animal-name">#${a.id} · ${a.nome}</div><div class="animal-details"><span>🐄 ${a.raca}</span><span>📅 ${a.lactDias} dias lact.</span><span>🔬 CCS ${a.ccs}k</span></div><div class="mt-2"><span class="badge ${a.status==='CCS Alto'?'badge-danger':a.status==='Atenção'?'badge-warning':''}">${a.status}</span></div></div><div class="animal-prod-area"><div class="animal-prod-value">${a.prod.toFixed(1)}</div><div class="animal-prod-label">litros/dia</div></div></div>`).join('')
  }
  function renderizarKPIs(){
    $('kpiContainer').innerHTML=`<div class="kpi-item"><div class="kpi-label">🥛 Produção</div><div class="kpi-value">${metricasGerais.producaoTotalDia} <span class="kpi-unit">L/dia</span></div><div class="kpi-trend">↑ 3% nos últimos 7 dias</div></div><div class="kpi-item"><div class="kpi-label">🐄 Lactação</div><div class="kpi-value">${metricasGerais.vacasLactacao}</div><div class="kpi-trend">de 78 vacas</div></div><div class="kpi-item"><div class="kpi-label">📊 Média/vaca</div><div class="kpi-value">${metricasGerais.mediaVaca} <span class="kpi-unit">L</span></div><div class="kpi-trend">meta 32 L</div></div><div class="kpi-item"><div class="kpi-label">🧪 CCS</div><div class="kpi-value">${metricasGerais.ccsMedio}k</div><div class="kpi-trend">${metricasGerais.ccsMedio>200?'⚠️ atenção':'✅ dentro da meta'}</div></div>`
  }
  function renderizarAlertas(){const alertas=animais.filter(a=>a.ccs>300);$('alertContainer').innerHTML=alertas.map(a=>`<div class="alert-line" style="border-left-color:#D9534F">🩺 <strong>${a.nome} (#${a.id})</strong> — CCS elevado (${a.ccs}k). <button style="border:0;background:none;color:var(--verde-base);font-weight:700;cursor:pointer" onclick="showTab('servicos')">Buscar veterinário →</button></div>`).join('')}
  function renderizarRanking(){
    const tbody=document.querySelector('#rankingTable tbody');tbody.innerHTML=rankingFazendas.map((f,i)=>`<tr ${f.nome.includes('São Pedro')?'style="background:#E8F3E8"':''}><td><strong>${f.nome}</strong></td><td>${f.producao} L</td><td>${i<3?['🥇','🥈','🥉'][i]:(i+1)+'º'}</td></tr>`).join('');
    const pos=rankingFazendas.findIndex(f=>f.nome.includes('São Pedro'))+1;$('rankPosicao').textContent=pos+'º lugar';$('progressScore').style.width=Math.min(100,(metricasGerais.mediaVaca/38)*100)+'%';$('custoLiteral').textContent=metricasGerais.custoLitro.toFixed(2).replace('.',',');$('custoProgress').style.width=Math.max(5,Math.min(100,((1.9-metricasGerais.custoLitro)/.8)*100))+'%'
  }
  function renderizarFinanceiro(){
    const now=new Date();const m=now.getMonth(),y=now.getFullYear();const mes=transacoes.filter(t=>{const d=new Date(t.data+'T12:00:00');return d.getMonth()===m&&d.getFullYear()===y});
    const receitas=mes.filter(t=>t.tipo==='receita').reduce((s,t)=>s+t.valor,0),despesas=mes.filter(t=>t.tipo==='despesa').reduce((s,t)=>s+t.valor,0),resultado=receitas-despesas;const prodMensal=metricasGerais.producaoTotalDia*30;const custo=despesas/(prodMensal||1),lucro=PRECO_MEDIO_LITRO-custo;
    $('finKpis').innerHTML=`<div class="kpi-item"><div class="kpi-label">Receitas (mês)</div><div class="kpi-value" style="color:#2E7D32;font-size:23px">${brl(receitas)}</div></div><div class="kpi-item"><div class="kpi-label">Despesas (mês)</div><div class="kpi-value" style="color:#C0392B;font-size:23px">${brl(despesas)}</div></div><div class="kpi-item"><div class="kpi-label">Resultado</div><div class="kpi-value" style="color:${resultado>=0?'#2E7D32':'#C0392B'};font-size:23px">${brl(resultado)}</div></div><div class="kpi-item"><div class="kpi-label">Custo estimado / L</div><div class="kpi-value" style="font-size:23px">${brl(custo)}</div></div>`;
    $('totalReceitasValor').textContent=brl(receitas);$('totalDespesasValor').textContent=brl(despesas);$('resultadoMes').textContent=brl(resultado);$('resultadoMes').style.color=resultado>=0?'#2E7D32':'#C0392B';$('custoTotalOperacional').textContent=brl(despesas);$('producaoTotalLitros').textContent=Math.round(prodMensal).toLocaleString('pt-BR')+' L';$('custoPorLitroValor').textContent=brl(custo);$('lucroPorLitro').textContent=brl(lucro);$('receitaProgress').style.width=(receitas?Math.min(100,receitas/Math.max(receitas,despesas)*100):0)+'%';$('despesaProgress').style.width=(despesas?Math.min(100,despesas/Math.max(receitas,despesas)*100):0)+'%';$('custoPorLitroBar').style.width=Math.min(100,custo/PRECO_MEDIO_LITRO*100)+'%';
    $('transacoesBody').innerHTML=[...transacoes].sort((a,b)=>b.id-a.id).slice(0,8).map(t=>`<tr><td>${new Date(t.data+'T12:00:00').toLocaleDateString('pt-BR')}</td><td>${t.descricao}</td><td>${t.categoria}</td><td>${t.tipo==='receita'?'💰 Receita':'📉 Despesa'}</td><td style="font-weight:700;color:${t.tipo==='receita'?'#2E7D32':'#C0392B'}">${brl(t.valor)}</td><td><button style="background:none;border:none;cursor:pointer" onclick="removerTransacao(${t.id})">🗑️</button></td></tr>`).join('')
  }
  function adicionarTransacao(tipo,data,descricao,categoria,valor){transacoes.push({id:nextTransacaoId++,tipo,data,descricao,categoria,valor:Number(valor)});salvarTudo();renderizarFinanceiro()}
  window.removerTransacao=id=>{transacoes=transacoes.filter(t=>t.id!==id);salvarTudo();renderizarFinanceiro();toast('Movimentação removida')}

  let serviceType='humanos',serviceCategory='Todos',nearbyOnly=false;
  function serviceDataset(){return serviceType==='humanos'?profissionais:maquinas}
  function renderServiceChips(){const cats=['Todos',...new Set(serviceDataset().map(x=>x.categoria))];$('serviceChips').innerHTML=cats.map(c=>`<button class="chip ${c===serviceCategory?'active':''}" onclick="setServiceCategory('${c}')">${c}</button>`).join('')}
  window.setServiceCategory=c=>{serviceCategory=c;renderServiceChips();renderServices()}
  function renderServices(){
    const q=$('serviceSearch').value.trim().toLowerCase();let data=serviceDataset().filter(s=>(serviceCategory==='Todos'||s.categoria===serviceCategory)&&(!nearbyOnly||s.distancia<=50)&&(!q||`${s.nome} ${s.servico} ${s.categoria}`.toLowerCase().includes(q)));
    $('serviceGrid').innerHTML=data.length?data.map(s=>`<div class="service-card"><div class="flex-between"><div class="service-icon">${s.icon}</div><span class="badge ${s.disponivel==='Hoje'?'':'badge-blue'}">${s.disponivel==='Hoje'?'✅ Hoje':'📅 '+s.disponivel}</span></div><div><div class="service-name">${s.servico}</div><div class="service-meta">${s.nome}</div></div><div class="service-meta">⭐ ${s.estrelas} (${s.avaliacoes}) · 📍 ${s.distancia} km</div><div class="service-price">${brl(s.preco)} <span class="subtle">/${s.unidade}</span></div><div class="flex-wrap"><button class="btn btn-small" style="flex:1" onclick="contratarServico('${s.id}')">Solicitar</button><button class="btn btn-outline btn-small" onclick="verServico('${s.id}')">Detalhes</button></div></div>`).join(''):'<div class="empty">Nenhum serviço encontrado com esses filtros.</div>'
  }
  window.verServico=id=>{const s=[...profissionais,...maquinas].find(x=>x.id===id);$('serviceDetailInner').innerHTML=`<div class="flex-between"><div class="service-icon">${s.icon}</div><span class="badge">⭐ ${s.estrelas}</span></div><h2 style="margin:12px 0 4px">${s.servico}</h2><div class="subtle">${s.nome} · 📍 ${s.distancia} km</div><p style="margin:15px 0;font-size:13px">${s.descricao}</p><div class="card" style="box-shadow:none"><div class="flex-between"><span>Valor base</span><strong class="service-price">${brl(s.preco)}/${s.unidade}</strong></div><div class="flex-between mt-2"><span>Disponibilidade</span><span class="badge">${s.disponivel}</span></div></div><button class="btn btn-block" onclick="closeModal('modalServiceDetail');contratarServico('${s.id}')">Solicitar orçamento</button>`;openModal('modalServiceDetail')}
  window.contratarServico=id=>{const s=[...profissionais,...maquinas].find(x=>x.id===id);$('servicoTipo').value=s.tipo==='humanos'?'Profissional':'Máquina';$('servicoNome').value=s.servico;$('selectedServiceSummary').style.display='block';$('selectedServiceSummary').innerHTML=`${s.icon} <strong>${s.servico}</strong><br><span class="subtle">${s.nome} · a partir de ${brl(s.preco)}/${s.unidade}</span>`;$('modalSolicitar').dataset.provider=s.nome;$('modalSolicitar').dataset.price=s.preco;openModal('modalSolicitar')}
  function renderSolicitacoes(){$('visitasBody').innerHTML=solicitacoes.length?[...solicitacoes].reverse().map(v=>`<tr><td>${new Date(v.data+'T12:00:00').toLocaleDateString('pt-BR')}</td><td>${v.servico}</td><td>${v.prestador}</td><td>${v.valor?brl(v.valor):'A orçar'}</td><td><span class="badge ${v.status.includes('Orçamento')?'badge-warning':''}">${v.status}</span></td><td>${v.valor&&!v.financeiro?`<button class="btn btn-outline btn-small" onclick="registrarServicoFinanceiro(${v.id})">→ Financeiro</button>`:v.financeiro?'<span class="badge">✓ Lançado</span>':''}</td></tr>`).join(''):'<tr><td colspan="6">Nenhuma solicitação.</td></tr>'}
  window.registrarServicoFinanceiro=id=>{const v=solicitacoes.find(x=>x.id===id);if(!v||!v.valor||v.financeiro)return;adicionarTransacao('despesa',v.data,`Serviço: ${v.servico}`,'Máquinas e Serviços',v.valor);v.financeiro=true;salvarTudo();renderSolicitacoes();toast('Serviço lançado no Financeiro')}

  let productCategory='Todos';
  function renderProductChips(){const cats=['Todos',...new Set(produtos.map(p=>p.categoria))];$('productChips').innerHTML=cats.map(c=>`<button class="chip ${c===productCategory?'active':''}" onclick="setProductCategory('${c}')">${c}</button>`).join('')}
  window.setProductCategory=c=>{productCategory=c;renderProductChips();renderProducts()}
  function renderProducts(){
    const q=$('productSearch').value.trim().toLowerCase();let data=produtos.filter(p=>(productCategory==='Todos'||p.categoria===productCategory)&&(!q||`${p.nome} ${p.categoria} ${p.loja}`.toLowerCase().includes(q)));const ord=$('sortProducts').value;if(ord==='menor')data=[...data].sort((a,b)=>a.preco-b.preco);if(ord==='maior')data=[...data].sort((a,b)=>b.preco-a.preco);
    $('productGrid').innerHTML=data.length?data.map(p=>`<div class="product-card"><div class="product-image"><span class="product-tag">${p.tag}</span>${p.icon}</div><div class="product-body"><div class="product-title">${p.nome}</div><div class="product-store">${p.loja} · ${p.avaliacao}</div><div><div class="product-price">${brl(p.preco)}</div><div class="product-installment">ou 3x de ${brl(p.preco/3)}</div></div><button class="btn btn-small" onclick="addToCart('${p.id}')">+ Adicionar ao carrinho</button></div></div>`).join(''):'<div class="empty">Nenhum produto encontrado.</div>'
  }
  window.addToCart=id=>{const item=cart.find(i=>i.id===id);if(item)item.qtd++;else cart.push({id,qtd:1});salvarTudo();renderCartCounts();toast('Produto adicionado ao carrinho')}
  window.changeQty=(id,delta)=>{const item=cart.find(i=>i.id===id);if(!item)return;item.qtd+=delta;if(item.qtd<=0)cart=cart.filter(i=>i.id!==id);salvarTudo();renderCart();renderCartCounts()}
  function cartTotal(){return cart.reduce((s,i)=>{const p=produtos.find(x=>x.id===i.id);return s+(p?p.preco*i.qtd:0)},0)}
  function renderCartCounts(){const n=cart.reduce((s,i)=>s+i.qtd,0);$('headerCartCount').textContent=n;$('heroCartCount').textContent=n;$('cartItemsBadge').textContent=n+' '+(n===1?'item':'itens')}
  function renderCart(){
    renderCartCounts();$('cartItems').innerHTML=cart.length?cart.map(i=>{const p=produtos.find(x=>x.id===i.id);return `<div class="cart-item"><div><strong>${p.icon} ${p.nome}</strong><div class="subtle">${brl(p.preco)} cada</div></div><div style="text-align:right"><div class="qty-controls"><button class="qty-btn" onclick="changeQty('${i.id}',-1)">−</button><strong>${i.qtd}</strong><button class="qty-btn" onclick="changeQty('${i.id}',1)">+</button></div><div class="subtle mt-2">${brl(p.preco*i.qtd)}</div></div></div>`}).join(''):'<div class="empty">Seu carrinho está vazio.</div>';$('cartTotal').textContent=brl(cartTotal());$('cartFooter').style.display=cart.length?'block':'none'
  }
  function openCart(){renderCart();openModal('modalCart')}

  function renderizarTudo(){renderizarKPIs();renderizarAlertas();renderizarAnimais();renderizarRanking();renderizarFinanceiro();renderServiceChips();renderServices();renderSolicitacoes();renderProductChips();renderProducts();renderCartCounts()}
  function openModal(id){$(id).classList.add('open');document.body.style.overflow='hidden'}
  window.closeModal=id=>{$(id).classList.remove('open');document.body.style.overflow=''}
  window.abrirAnimal=id=>{const a=animais.find(x=>x.id===id);$('modalAnimalInner').innerHTML=`<div class="card-title">🐄 ${a.nome}</div><div><strong>#${a.id}</strong> · ${a.raca}<br><br>📊 Produção: <strong>${a.prod} L/dia</strong><br>🔬 CCS: ${a.ccs}k<br>📅 Dias em lactação: ${a.lactDias}<br>⚖️ Peso: ${a.peso}<br><br><span class="badge">${a.status}</span></div>`;openModal('modalAnimalDetail')}
  window.showTab=tabId=>{document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));$('panel-'+tabId).classList.add('active');document.querySelectorAll('.tab-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===tabId));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.mobileTab===tabId));window.scrollTo({top:0,behavior:'smooth'})}
